---
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/db_apirest?serverTimezone=Europe/Madrid
    username: mamp
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
logging:
  level: 
    org.hibernate.sql: debug
    
#logging.level.org.hibernate.SQL=debug
